### PR TITLE
[ENH] Add single docker compose recipe for all deployment flavours

### PR DESCRIPTION
**Pull request by surchs**
- Closes #

Changes proposed in this pull request:

-
-

## Checklist
_This section is for the PR reviewer_

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Comment by surchs** [comment]
@alyssadai  was this an intentional close? I think the draft was pretty close to done, no?

**Comment by alyssadai** [comment]
@surchs yes - I renamed the branch to something more informative so I will reopen the PR from the new branch. Probably there was a way to do that without closing this PR, sorry if it alarmed you 😅

**Comment by alyssadai** [comment]
Replaced by https://github.com/neurobagel/recipes/pull/32

**Comment by surchs** [comment]
> @surchs yes - I renamed the branch to something more informative so I will reopen the PR from the new branch. Probably there was a way to do that without closing this PR, sorry if it alarmed you 😅 

image

**Pull request closed without merging**
